### ISSUE TITLE
建议移除 `public/电路分析基础C/电路第五版46528--作者样 (1).pdf`

### ISSUE THREAD

**Issue by BlockLune** [NJUPTFreeExams/NJUPT-General-Free-Exams#46]
这份资料似乎属于 [UploadGuide](https://njuptfreeexams.github.io/UploadGuide.html) “什么资料不适合上传” 中的 `电子版的书籍`，且空间占用很大，建议删除。

**Comment by Dilettante258** [comment]
我觉得可以。请你一并做了。

**Comment by BlockLune** [comment]
已在 #49 中移除该文件。
