### ISSUE TITLE
关于 `src/content/docs/reserve` 目录的用途

### ISSUE THREAD

**Issue by BlockLune** [NJUPTFreeExams/NJUPT-General-Free-Exams#47]
请问 src/content/docs/reserve 这个目录的用途是什么？其中的文件似乎在 public 中也有。如果我想要更新的话，我应该更新哪一边呢？

**Comment by BlockLune** [comment]
哦哦我似乎明白了，这个目录中的内容直接会在[新主页](https://njuptfreeexams.netlify.app/)显示出来是吗？

**Comment by Dilettante258** [comment]
之前没看Issue, 刚刚在PR里回你了，这里再复制一遍。

因为在`/public/`文件夹下文件都不会自动构建网页。所以如果你上传的md文件想要也有一个网页的话，建议再复制一份到`src/content/docs/reserve`文件夹下，并加上frontmatter。并在该课程的Readme下参照相对路径，加上网页链接。

`reserve`这个名字我随便想的，如果有其他建议欢迎提出。另，docs文件夹下各学院名单我是根据各学院官网的前缀取的，*也许可以改一下*？

**Comment by M-10777** [comment]
更新一下帮助文档 `src/content/docs/homepage/UploadGuide.md` ？
里面的内容有点老了，不适合现在的目录结构。

**Comment by Dilettante258** [comment]
好，这几天内改。
@M-10777
