### ISSUE TITLE
关于 `数据结构` 相关内容所属仓库的问题

### ISSUE THREAD

**Issue by BlockLune** [NJUPTFreeExams/NJUPT-General-Free-Exams#48]
`数据结构` 相关内容是否应当放在 [NJUPT-CS-FREE](https://github.com/NJUPTFreeExams/NJUPT-CS-FREE) 这个 repo 中更为合适？@Dilettante258

**Comment by Dilettante258** [comment]
我很久之前想过。但是我发现像离散数学这种课也放这个仓库了，然后我补充资料就只在这个仓库补充了。

个人觉得一个仓库可以放下所有课程就没必要开多个仓库，因为要检查多个仓库是很费时费力的。算是一个历史遗留问题了。

**Comment by BlockLune** [comment]
也许应该按 #6 说的，用一下 submodule 或者 subtree 的功能。现在这个仓库有点太大了，clone 一下要一个多 G。

**Comment by Dilettante258** [comment]
> 也许应该按 #6 说的，用一下 submodule 或者 subtree 的功能。现在这个仓库有点太大了，clone 一下要一个多 G。

这个也想过，但是挺复杂的，如果这么做，就需要分`public`文件夹下的内容到几个repo去。

我个人是觉得，一方面如果有Github Pro可以用Codespace来在线管理，另一方面，简单的通过Github页面的Edit和Upload files也是可行的。

![image](https://github.com/NJUPTFreeExams/NJUPT-General-Free-Exams/assets/113875344/5c4eefbd-f8db-44af-9f52-d7390c4c70b9)

如果你愿意用 submodule 或者 subtree ，那么你先来试试？Netlify有检查功能。
