### ISSUE TITLE
想要更新技术经济学 怎么才能获得库的push权？

### ISSUE THREAD

**Issue by LR1093141031** [NJUPTFreeExams/NJUPT-General-Free-Exams#5]

**Comment by LR1093141031** [comment]
[技术经济学 闻超群课件.zip](https://github.com/NJUPTFreeExams/NJUPT-General-Free-Exams/files/3341417/default.zip)
[技术经济学复习提纲.pdf](https://github.com/NJUPTFreeExams/NJUPT-General-Free-Exams/files/3341418/default.pdf)
[技术经济学重点公式.pdf](https://github.com/NJUPTFreeExams/NJUPT-General-Free-Exams/files/3341419/default.pdf)

**Comment by ZsgsDesign** [comment]
Please **fork** it first and then submit **Pull Request**.

**Fork:** the right-most button on the top side.

**Pull Request:** Open your forked repo, make changes like uploading files or so on, and then click **Create Pull Request**, left branch click **master@NJUPTFreeExams/NJUPT-General-Free-Exams** and right branch click **master@LR1093141031/NJUPT-General-Free-Exams**.

Happy contributing.
