### ISSUE TITLE
建议规范化 `src/content/docs` 的目录及文件命名

### ISSUE THREAD

**Issue by BlockLune** [NJUPTFreeExams/NJUPT-General-Free-Exams#50]
目前，该目录下的字目录命名存在首字母大写和全小写两种命名方式，建议选择其中一种。并且，理学院对应的字目录直接使用拼音首字母 `lxy` 与其他学院的对应英文命名方法也不一样，建议更改。

**Comment by Dilettante258** [comment]
`docs`文件夹下各学院名单差不多是根据各学院官网的前缀取的，因为当时对于如何统一命名有些问题，所以就摆烂这么做了。我觉得可以先讨论出如何统一命名。 
#47 目录命名问题。

**Comment by toulzx** [comment]
> 目前，该目录下的字目录命名存在首字母大写和全小写两种命名方式，建议选择其中一种。并且，理学院对应的字目录直接使用拼音首字母 `lxy` 与其他学院的对应英文命名方法也不一样，建议更改。

确实，感觉看得有点乱😂

**Comment by BlockLune** [comment]
@toulzx @Dilettante258 请看一下 #72 中的更改，已经更新了相关命名

**Comment by toulzx** [comment]
> @Dilettante258 @toulzx 来讨论一下吧！我觉得其实只有一个理学院需要改一下，从 lxy 这样的拼音改成 school-of-science 之类的即可。类似于外国语学院的 FLS 表示的 Foreign Lang School

可以~
