### ISSUE TITLE
建议移除 `public/大学英语/学术英语.社科.第二版(教师用书).pdf`

### ISSUE THREAD

**Issue by BlockLune** [NJUPTFreeExams/NJUPT-General-Free-Exams#62]
类似于 #46 ，该资料属于 [UploadGuide](https://njuptfreeexams.github.io/UploadGuide.html) “什么资料不适合上传” 中的 `电子版的书籍`，且空间占用很大，建议删除。

**Comment by Dilettante258** [comment]
假期我来处理一下。很多理工科同学 _大学英语4_ 就是上的《学术英语（社科）》，教师用书里面有课后系统答案，可以减轻不少麻烦。
我觉得可以删除后留一个网盘链接，当然也可以全删了，不知道你的意见如何。

**Comment by BlockLune** [comment]
我觉得可以留个链接，或者最好是能把答案单独弄出来，整本书有 70M 太大了

**Comment by Dilettante258** [comment]
> 我觉得可以留个链接，或者最好是能把答案单独弄出来，整本书有 70M 太大了

好，等我考完了我来处理吧。
