### ISSUE TITLE
建议在  public/信号与系统A  中上传课后习题答案

### ISSUE THREAD

**Issue by ziheng5** [NJUPTFreeExams/NJUPT-General-Free-Exams#69]
[信号2020-2021-1课后习题答案.pdf](https://github.com/user-attachments/files/16921523/2020-2021-1.pdf)

**Comment by Sodium2He** [comment]
https://github.com/NJUPTFreeExams/NJUPT-General-Free-Exams/pull/71#issue-2657282412
已创建 Pull Request
