### ISSUE TITLE
为啥我没看到有高数A上的资料呢

### ISSUE THREAD

**Issue by LightningLeader** [NJUPTFreeExams/NJUPT-General-Free-Exams#7]
。。。RT。。。没找到高数A上，只有高数下。。。。

**Comment by imguozr** [comment]
To be honest, I enrolled in this course more than 4 years ago and a lot of materials can not be found now. We need help from current students.

**Comment by AlexLeelc** [comment]
yeah,I found something invalid.

**Comment by imguozr** [comment]
We now have [some materials](https://github.com/NJUPTFreeExams/NJUPT-General-Free-Exams/tree/master/高等数学A(上)) thanks to @Xander-C ! This issue will be closed.
