### ISSUE TITLE
建议将本仓库文档与 njuptfreeexams.github.io 中的文档进行区分

### ISSUE THREAD

**Issue by toulzx** [NJUPTFreeExams/NJUPT-General-Free-Exams#70]
#45 有个 [UploadGuide.mdx](https://github.com/NJUPTFreeExams/NJUPT-General-Free-Exams/blob/master/src/content/docs/homepage/UploadGuide.mdx)，专门适用于本仓库的结构变化，
之后可能需要和 njuptfreeexams.github.io 这边的 UploadGuide 等文档区分/对齐一下，避免歧义或混淆。

**Comment by toulzx** [comment]
我之前在 njuptfreeexams.github.io 有 PR[#5](https://github.com/NJUPTFreeExams/njuptfreeexams.github.io/pull/5) 到 feature 分支，需要评估一下合并。

**Comment by BlockLune** [comment]
@toulzx 请您查看一下 #72，我整合了几份指南。另一件事是，我认为让 njuptfreeexams.github.io 直接跳转到新的 [njuptfreeexams.netlify.app](https://njuptfreeexams.netlify.app/) 首页会比较好，这样不需要维护两份内容。

**Comment by BlockLune** [comment]
我注意到我遗漏了关于复制一份 markdown 的说明，需要补上。

**Comment by toulzx** [comment]
> @toulzx 请您查看一下 #72，我整合了几份指南。另一件事是，我认为让 njuptfreeexams.github.io 直接跳转到新的 [njuptfreeexams.netlify.app](https://njuptfreeexams.netlify.app/) 首页会比较好，这样不需要维护两份内容。

njuptfreeexams.github.io 链接了通识课仓库外的其它学院专业课程仓库，那些没有上线 netlify.app

**Comment by BlockLune** [comment]
> > @toulzx 请您查看一下 #72，我整合了几份指南。另一件事是，我认为让 njuptfreeexams.github.io 直接跳转到新的 [njuptfreeexams.netlify.app](https://njuptfreeexams.netlify.app/) 首页会比较好，这样不需要维护两份内容。
> 
> njuptfreeexams.github.io 链接了通识课仓库外的其它学院专业课程仓库，那些没有上线 netlify.app

在 #72 中已经添加了相关链接，并且我说明了 general 仓库的特殊性，您看一下

![image](https://github.com/user-attachments/assets/7d31b510-83a7-4e91-8e7c-d1b465600aa5)

**Comment by toulzx** [comment]
> > > @toulzx 请您查看一下 #72，我整合了几份指南。另一件事是，我认为让 njuptfreeexams.github.io 直接跳转到新的 [njuptfreeexams.netlify.app](https://njuptfreeexams.netlify.app/) 首页会比较好，这样不需要维护两份内容。
> > 
> > 
> > njuptfreeexams.github.io 链接了通识课仓库外的其它学院专业课程仓库，那些没有上线 netlify.app
> 
> 在 #72 中已经添加了相关链接，并且我说明了 general 仓库的特殊性，您看一下
> 

哦哦，现在看到了，review 的时候跳过了~
那没问题，如果文档已经整合了，可以把 njuptfreeexams.github.io 重定向过去 :)

**Comment by BlockLune** [comment]
那边已经合并了，见[新的门户网站](https://njuptfreeexams.netlify.app/)。
